server:
  port: 9990
  

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajaygaikwad774/cloud-config-server
          clone-on-start: true