spring:
  h2:
    console:
      enabled: true  application:    name: user-ws
  jackson:    time-zone: Asia/Kolkata
  zipkin:    base-url: http://127.0.0.1:9411/

server:  port: 8006   
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always